Feat/create task
DeveloperBreakfast/wedothings-client pull request #8
Opened 2021-12-12 22:50 UTC by Michael-Liendo

Everything is alright?

2021-12-13 02:46 UTC, EstebanBorai commented on src/components/Layout/index.jsx
> +      </main>
We have 2 issues here:

1. We have two elements with the same ID, you should use the `id` attribute for a single element.
2. We have 2 `<main>` tags which is invalid, you must have a single one.

```suggestion
      <main id="layout-main">
          {props.children}
      </main>
```

2021-12-13 02:47 UTC, EstebanBorai commented on src/components/Main/Modal/Modal.jsx
> +const Modal = (props) => {
Please use `function` syntax instead.

```suggestion
function Modal(props) {
```

2021-12-13 02:47 UTC, EstebanBorai commented on src/components/Main/Modal/Modal.jsx
> +};
As this is a reusable component, you probably want to have `children` here, instead of these elements.

2021-12-13 02:48 UTC, EstebanBorai commented on src/components/Main/Modal/Modal.jsx
> +  setModal: PropTypes.func.isRequired,
I would use `onClose` instead, you likely to unmount this component from the parent.

2021-12-13 02:48 UTC, EstebanBorai commented on src/components/Main/index.jsx
> +    </div>
Avoid leaving empty lines.

```suggestion
    <div>
      <h1>Hello, {props.currentUser.name}!</h1>
      <button onClick={() => setModal(true)} className="ui green button">
        New Task
      </button>
      {modal ? <Modal setModal={setModal}/> : null}
    </div>
```

2021-12-13 02:49 UTC, EstebanBorai commented on src/components/Main/index.jsx
> +const Main = (props) => {
Use `function` syntax for components please.

2021-12-13 02:49 UTC, EstebanBorai commented on src/components/Main/index.jsx
> +import Modal from './Modal/Modal';
```suggestion
import Modal from './Modal/Modal';

import './Main.css';
```

2021-12-13 02:49 UTC, EstebanBorai requested changes
Avoid pushing empty files. Remove `Main.css`

2021-12-13 03:42 UTC, Michael-Liendo commented on src/components/Main/Modal/Modal.jsx
> +};
please explain more in detail

2021-12-13 03:42 UTC, Michael-Liendo commented on src/components/Main/Modal/Modal.jsx
> +  setModal: PropTypes.func.isRequired,
please explain more in detail

2021-12-13 03:51 UTC, EstebanBorai commented on src/components/Main/Modal/Modal.jsx
> +  setModal: PropTypes.func.isRequired,
`setModal` is not an intuitive name for this method.

Usually you want to handle open/close state of a modal from the parent, then you have a callback/event listener for the closing/opening action events.

Check this out: https://react-bootstrap.netlify.app/components/modal/#modals-live

There you have the modal and the container component in the same component. What you actually want to achieve is having both of them disengaged.

2021-12-13 03:52 UTC, EstebanBorai requested changes
Modal behavior could improve.
Task creation is still missing.

2021-12-15 05:12 UTC, dararod approved these changes

2021-12-15 05:14 UTC, EstebanBorai commented
I've implemented the `<Modal />` component to be used in this feature. I'm merging this to `main` in order to also have a better starting point.

Features missing are:

- Close button icon
- Better state management for modal (so many passing props)

2021-12-15 05:15 UTC, EstebanBorai approved these changes

2021-12-15 05:15 UTC, merged